// <auto-generated />
namespace WebUI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class changed_the_recipt_id_to_long_data_type1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changed_the_recipt_id_to_long_data_type1));
        
        string IMigrationMetadata.Id
        {
            get { return "201410120957036_changed_the_recipt_id_to_long_data_type1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
