// <auto-generated />
namespace WebUI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Included_liveMatchesTable5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Included_liveMatchesTable5));
        
        string IMigrationMetadata.Id
        {
            get { return "201410291117080_Included_liveMatchesTable5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
