// <auto-generated />
namespace WebUI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class chnaged_setdate_tostring_in_live_matches : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(chnaged_setdate_tostring_in_live_matches));
        
        string IMigrationMetadata.Id
        {
            get { return "201411140548524_chnaged_setdate_tostring_in_live_matches"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
