// <auto-generated />
namespace WebUI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class MatchOddError : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MatchOddError));
        
        string IMigrationMetadata.Id
        {
            get { return "201410172202302_MatchOddError"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
